defaults:
  permissions:
    - ecm/user_area/backend/engine
    - ecm/user_area/permission/index
    - ecm/user_area/permission/show
    - ecm/user_area/permission/new
    - ecm/user_area/permission/create
    - ecm/user_area/permission/edit
    - ecm/user_area/permission/update
    - ecm/user_area/permission/destroy
    - ecm/user_area/role/index
    - ecm/user_area/role/show
    - ecm/user_area/role/new
    - ecm/user_area/role/create
    - ecm/user_area/role/edit
    - ecm/user_area/role/update
    - ecm/user_area/role/destroy
    - user/index
    - user/show
    - user/new
    - user/create
    - user/edit
    - user/update
    - user/destroy
  roles:
    ecm/user_area/administrator:
      - ecm/user_area/backend/engine
      - ecm/user_area/permission/index
      - ecm/user_area/permission/show
      - ecm/user_area/permission/new
      - ecm/user_area/permission/create
      - ecm/user_area/permission/edit
      - ecm/user_area/permission/update
      - ecm/user_area/permission/destroy
      - ecm/user_area/role/index
      - ecm/user_area/role/show
      - ecm/user_area/role/new
      - ecm/user_area/role/create
      - ecm/user_area/role/edit
      - ecm/user_area/role/update
      - ecm/user_area/role/destroy
      - user/index
      - user/show
      - user/new
      - user/create
      - user/edit
      - user/update
      - user/destroy
    ecm/user_area/reviewer:
      - ecm/user_area/backend/engine
      - ecm/user_area/permission/index
      - ecm/user_area/permission/show
      - ecm/user_area/role/index
      - ecm/user_area/role/show
      - user/index
      - user/show